// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OO1sWZyDNwnxBCNjXP0aiGOxfPrge2g',
    appId: '1:710857205681:web:7fbd2082b8b3232fb3ff90',
    messagingSenderId: '710857205681',
    projectId: 'flutter-firebase-auth-8b00b',
    authDomain: 'flutter-firebase-auth-8b00b.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-8b00b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPbp1h0ZyRN_FC8WyikXSoNnGk18EiLM',
    appId: '1:710857205681:android:fdbc21ec43994dc1b3ff90',
    messagingSenderId: '710857205681',
    projectId: 'flutter-firebase-auth-8b00b',
    storageBucket: 'flutter-firebase-auth-8b00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDun1aT8_bHKfx_ksf8N_zL-Ea-rtfgDcw',
    appId: '1:710857205681:ios:0691a0a429e9f127b3ff90',
    messagingSenderId: '710857205681',
    projectId: 'flutter-firebase-auth-8b00b',
    storageBucket: 'flutter-firebase-auth-8b00b.appspot.com',
    iosClientId: '710857205681-61kea1gt4r3iuscm5q4casplhtu7r0li.apps.googleusercontent.com',
    iosBundleId: 'com.arisesoft.flutter-firebase-auth',
  );
}
